- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy configuration files
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Remove file 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: restarted
