- name: Configuring Node JS repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Node Js
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Call User Pre-req
  ansible.builtin.include_tasks:
    file: user_preq.yml

- name: Install dependent files for App 
  ansible.builtin.shell: npm install 
  chdir: /app

- name: Call Schema
  ansible.builtin.include_tasks:
    file: schema.yml

- name: Call Service Systemd
  ansible.builtin.include_tasks:
    file: service_systemd.yml


