- name: Copy {{component}}.service
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start service {{component}}, if not started
  ansible.builtin.service:
    name: "{{component}}"
    enabled: true
    state: restarted
    daemon_reload: true
